import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
 
import { SonnerToaster } from '@/components/ui/sonner-toaster';
import { Analytics } from "@vercel/analytics/react";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import AppProvider from '@/components/app-provider';
import Boostrap from '@/components/bootstrap';
 
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
         {children} 
        </AppProvider>
        <SonnerToaster/>
         <Analytics />
         <Boostrap/>
         <TailwindIndicator />
      </body>
    </html>
  )
}
